---
title: "Writing Functions"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
```


```{r}
knitr::opts_chunk$set(
        echo = TRUE,
        warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() +theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Writing my first function

As an example, here's a z-score computation.

```{r}
x_vec = rnorm(n = 25, mean = 10, sd = 3.5)

(x_vec - mean(x_vec)) / sd(x_vec)
```

Now I'll write a function to do this.

```{r}
z_scores = function(x) {
  
  if(!is.numeric(x)) {
    stop("x needs to be numeric")
  }
  
  if(length(x) < 5) {
    stop("you need at least five numbers to comput the z score")
  }
  
  z = (x - mean(x)) / sd(x)
  
  return(z)
  
}

z_scores(x = x_vec)
```

Does this always work?

```{r, error = TRUE}
z_scores(x = 3)
z_scores(x = c("my", "name", "is", "Tamara"))

z_scores(x = x_vec)
```

